import turtle as t
t.pensize(5)
t.speed(1)
t.color('red')
t.begin_fill()
t.fillcolor('black')
t.left(150)
t.forward(180)
t.circle(-90,180)
t.setheading(60)
t.circle(-90,180)
t.forward(180)
t.end_fill()
t.hideturtle()
t.done()
